const carData = [
  {
    id: 1,
    carImage: "https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_default/v1/editorial/volkswagen-golf-gti-my20-1001x565-(1).jpg",
    carMake: "Volkswagen",
    carName: 'Golf',
    carYear: 2024,
    carPrice: "$30,000",
    carCategory: "Hatchback",
    carMileage: "30,000 miles",
    carEngine: "2000cc / 180HP",
    carTransmission: "Automatic",
    carFuel: "Petrol",
    carDescription: "The Volkswagen Golf GTI is a popular hatchback known for its sporty performance and comfortable driving experience."
  },
  {
    id: 2,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoCwgY0ftYiWRXfoJC8fzcsYUt1O1_0cW0LQ&s",
    carMake: "Toyota",
    carName: 'Camry',
    carYear: 2023,
    carPrice: "$25,000",
    carCategory: "Saloon",
    carMileage: "25,000 miles",
    carEngine: "2500cc / 200HP",
    carTransmission: "Automatic",
    carFuel: "Diesel",
    carDescription: "The Toyota Camry is a reliable and spacious sedan, perfect for daily commuting with its fuel-efficient diesel engine."
  },
  {
    id: 3,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGehkFifyb2YeT0pphotnSMRZLxaEPD62gcA&s",
    carMake: "Jeep",
    carName: 'Trackhawk',
    carYear: 2022,
    carPrice: "$20,000",
    carCategory: "SUV",
    carMileage: "20,000 miles",
    carEngine: "1800cc / 150HP",
    carTransmission: "Manual",
    carFuel: "Petrol",
    carDescription: "The Jeep Trackhawk is a powerful SUV designed for off-road adventures, equipped with a manual transmission for enthusiast drivers."
  },
  {
    id: 4,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1FqI_eUmJFC2QjNLHkdiEzE5KEpp9lkq-oQ&s",
    carMake: "Volkswagen",
    carName: 'Passat',
    carYear: 2023,
    carPrice: "$28,000",
    carCategory: "Wagon",
    carMileage: "18,000 miles",
    carEngine: "2200cc / 190HP",
    carTransmission: "Automatic",
    carFuel: "Petrol",
    carDescription: "The Volkswagen Passat is a versatile wagon known for its spacious interior and smooth automatic transmission."
  },
  {
    id: 5,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxySXPleRuUDHVknh5gNcW2XLR2fiTafIk1g&s",
    carMake: "Toyota",
    carName: 'Vellfire',
    carYear: 2023,
    carPrice: "$27,500",
    carCategory: "Minivan",
    carMileage: "22,000 miles",
    carEngine: "2000cc / 180HP",
    carTransmission: "Automatic",
    carFuel: "Petrol",
    carDescription: "The Toyota Vellfire is a luxurious minivan, offering ample space and comfort with its automatic transmission and powerful engine."
  },
  {
    id: 6,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0XVrlRCKN8-S7TnbXwiJGE3HJ1XHaJg09cg&s",
    carMake: "Volkswagen",
    carName: 'Touareg',
    carYear: 2022,
    carPrice: "$24,000",
    carCategory: "SUV",
    carMileage: "28,000 miles",
    carEngine: "3000cc / 250HP",
    carTransmission: "Automatic",
    carFuel: "Diesel",
    carDescription: "The Volkswagen Touareg is a robust SUV known for its powerful diesel engine and luxurious features, perfect for adventurous drives."
  },
  {
    id: 7,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvidpwAU6rzIHLNEJqoVz9SO4x8xtRStDyVQ&s",
    carMake: "BMW",
    carName: '3 Series',
    carYear: 2023,
    carPrice: "$22,500",
    carCategory: "Sedan",
    carMileage: "15,000 miles",
    carEngine: "1800cc / 150HP",
    carTransmission: "Manual",
    carFuel: "Petrol",
    carDescription: "The BMW 3 Series is a classic sedan known for its sporty performance and elegant design, featuring a manual transmission for enthusiasts."
  },
  {
    id: 8,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZRtmihezmTPDqhJr8ogQy40fsPhRy_SM6-g&s",
    carMake: "Ford",
    carName: 'Ranger',
    carYear: 2024,
    carPrice: "$32,000",
    carCategory: "Pickup",
    carMileage: "10,000 miles",
    carEngine: "3500cc / 300HP",
    carTransmission: "Automatic",
    carFuel: "Petrol",
    carDescription: "The Ford Ranger is a robust pickup truck with powerful engine options, perfect for both work and leisure activities."
  },
  {
    id: 9,
    carImage: "https://truckandfreight.co.za/wp-content/uploads/2022/08/Lead-Image-Faw-JH6-420-HP-004_880x500.jpeg",
    carMake: "Scania",
    carName: 'MAN',
    carYear: 2022,
    carPrice: "$18,000",
    carCategory: "Trucks",
    carMileage: "25,000 miles",
    carEngine: "1500cc / 120HP",
    carTransmission: "Manual",
    carFuel: "Petrol",
    carDescription: "The Scania MAN is a powerful truck designed for heavy-duty transport, featuring a manual transmission and robust engine."
  },
  {
    id: 10,
    carImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeVWN3P5cyChBEBSAOMzq94SZKbNw-7cyoRw&s",
    carMake: "Mazda",
    carName: 'Atenza',
    carYear: 2023,
    carPrice: "$26,000",
    carCategory: "Wagon",
    carMileage: "12,000 miles",
    carEngine: "2500cc / 200HP",
    carTransmission: "Automatic",
    carFuel: "Petrol",
    carDescription: "The Mazda Atenza is a stylish wagon known for its reliability and smooth automatic transmission, ideal for family outings."
  }
];

export default carData;
